### ISSUE TITLE
Unable to install dependencies?

### ISSUE THREAD

**Issue by anthonysetiadi** [chetanverma16/react-portfolio-template#36]
Have followed instructions on installing dependencies following clone using yarn however keep coming across errors. 

Could this be due to breaking updated dependencies that haven't been updated in package.json?

Here's my stack trace:
 ```bash
yarn install v1.22.18
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "gatsby > eslint-plugin-graphql > graphql-config > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.0.0" has unmet peer dependency "typescript@>=2.7".
warning "gatsby-plugin-sass > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[4/4] 🔨  Building fresh packages...
[-/15] ⡀ waiting...
[9/15] ⡀ sharp
[12/15] ⡀ mozjpeg
[10/15] ⡀ node-sass
error /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/node-sass
Output:
Building: /opt/homebrew/Cellar/node/16.3.0/bin/node /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/opt/homebrew/Cellar/node/16.3.0/bin/node',
gyp verb cli   '/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.3.0 | darwin | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:80:29)
gyp ERR! stack     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/which/which.js:89:16
gyp ERR! stack     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:195:21)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/opt/homebrew/Cellar/node/16.3.0/bin/node" "/Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/anthonysetiadi/Documents/antz.dev/react-templates/react-portfolio-template/node_modules/node-sass
gyp ERR! node -v v16.3.0
gyp ERR! node-gyp -v v3.8.0
```

**Comment by anthonysetiadi** [comment]
I've figured out my issue. I was using the wrong version of node. Downgraded node to v.14 and now it works. Closing issue.
